Updated to a copy of corenominal's most recent pipemenu master repo, changed chromium and chrome references to adapt to new package names.

diff --git a/cbpp-pipemenus/data/usr/bin/cbpp-compositor b/cbpp-pipemenus/data/usr/bin/cbpp-compositor
--- a/cbpp-pipemenus/data/usr/bin/cbpp-compositor
+++ b/cbpp-pipemenus/data/usr/bin/cbpp-compositor
@@ -3,98 +3,66 @@
 # Openbox Pipe Menu for use with compton compositor
 # Written for CrunchBang Linux <http://crunchbang.org/>
 # by Philip Newborough <corenominal@corenominal.org>
-# updated by Ben Young <computermouth@crunchbangplusplus.org>
-# for #!++ <https://crunchbangplusplus.org>
+# Ported to #!++ <https://crunchbangplusplus.org>
+# by Ben Young <computermouth@crunchbangplusplus.org>
+
+RESTART_ATTEMPTS=20
+
+if ! . cbpp-include.cfg 2> /dev/null; then
+    echo '  Failed to locate cbpp-include.cfg in PATH' >&2
+    exit 1
+fi
 
 # ------------- Set xcompmgr command options -----------------------------------
+EXECXCOMP='compton'
 if glxinfo | egrep -iq 'direct rendering: yes'; then
-    EXECXCOMP='compton --vsync opengl'
-else
-    EXECXCOMP='compton'
+    EXECXCOMP+=' --vsync opengl'
 fi
 
 # Edit xcompmgr settings
-if [ "$1" = "--edit" ]; then
-    if [ ! -f /home/$USER/.config/compton.conf ]; then
-        cp /etc/xdg/compton.conf /home/$USER/.config/compton.conf
-    fi
-    if [ -x "/usr/bin/geany" ]; then
-        geany /home/$USER/.config/compton.conf &
+if [[ $1 = '--edit' ]]; then
+    [[ ! -f $HOME/.config/compton.conf ]] &&
+        cp '/etc/xdg/compton.conf' "$HOME/.config/compton.conf"
+    
+    if [[ -x /usr/bin/geany ]]; then
+        geany "$HOME/.config/compton.conf" &
     else
-        terminator --command="nano /home/$USER/.config/compton.conf"
+        terminator --command='nano "$HOME/.config/compton.conf"'
     fi
-    exit 0
-fi
-
-# Toggle compositing with compton. Called with "cbpp-compositor --toggle"
-if [ "$1" = "--toggle" ] || [ "$1" = "--start" ]; then 
-    if [ ! "$(pidof compton)" ]; then
-      $EXECXCOMP &
+elif [[ $1 = '--toggle' || $1 = '--start' ]]; then # Toggle compositing with compton. 
+    # TODO why --toggle and --start act exactly the same?
+    if ! pidof compton > /dev/null; then
+        $EXECXCOMP &
     else
-      killall compton
+        killall compton
     fi
-    exit 0
-fi
-
-if [ "$1" = "--restart" ]; then
-    if [ "$(pidof compton)" ]; then
-        killall compton && sleep 1s
-        cbpp-compositor --start
-    fi
-    exit 0
-fi
-if [ "$1" = "--watch" ]; then
-    while inotifywait -e modify /home/$USER/.config/compton.conf; do
-        cbpp-compositor --restart
+elif [[ $1 = '--restart' ]]; then
+    killall -q compton
+    for (( i=0; i < RESTART_ATTEMPTS; i++ )); do
+        pidof compton > /dev/null || # no process found! Safe to start again
+            break
+            
+        (( i == RESTART_ATTEMPTS - 1 )) && # still didn't die? Probably hangs. Force it to die!
+            killall -q -S KILL compton
+            
+        sleep 0.25
     done
-    exit 0
-fi
-# Output Openbox menu
-if [ ! "$(pidof compton)" ]; then
-    cat << _EOF_
-    <openbox_pipe_menu>
-	    <item label="Enable Compositing">
-            <action name="Execute">
-				<command>
-					cbpp-compositor --start
-				</command>
-			</action>
-		</item>
-		<item label="Edit Compositing Settings">
-            <action name="Execute">
-				<command>
-					cbpp-compositor --edit
-				</command>
-			</action>
-		</item>
-    </openbox_pipe_menu>
-_EOF_
+    cbpp-compositor --start
+elif [[ $1 = '--watch' ]]; then
+    while inotifywait -e modify "$HOME/.config/compton.conf"; do
+        cbpp-compositor --restart # TODO move this to function?
+    done
 else
-    cat << _EOF_
-    <openbox_pipe_menu>
-				<item label="Restart Compositing">
-					<action name="Execute">
-						<command>
-							cbpp-compositor --restart
-						</command>
-					</action>
-				</item>
-				<item label="Disable Compositing">
-					<action name="Execute">
-						<command>
-							cbpp-compositor --toggle
-						</command>
-					</action>
-				</item>
-                <separator/>
-                <item label="Edit Compositing Settings">
-                    <action name="Execute">
-                        <command>
-                            cbpp-compositor --edit
-                        </command>
-                    </action>
-                </item>
-    </openbox_pipe_menu>
-_EOF_
+    # Output Openbox menu
+    menuStart
+    if ! pidof compton > /dev/null; then
+        menuItem 'Enable Compositing' 'cbpp-compositor --start'
+    else
+        menuItem 'Restart Compositing' 'cbpp-compositor --restart'
+        menuItem 'Disable Compositing' 'cbpp-compositor --toggle'
+        menuSeparator
+    fi
+    menuItem 'Edit Compositing Settings' 'cbpp-compositor --edit'
+    menuEnd
 fi
 exit 0
diff --git a/cbpp-pipemenus/data/usr/bin/cbpp-dropbox-pipemenu b/cbpp-pipemenus/data/usr/bin/cbpp-dropbox-pipemenu
--- a/cbpp-pipemenus/data/usr/bin/cbpp-dropbox-pipemenu
+++ b/cbpp-pipemenus/data/usr/bin/cbpp-dropbox-pipemenu
@@ -1,201 +1,123 @@
-#!/bin/sh
+#!/bin/bash
 # --------------------------------------------------------------------
 # An Openbox pipemenu for use with Dropbox and CrunchBang Linux.
 # Written for CrunchBang Linux <http://crunchbanglinux.org/>
 # by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
-# updated by Ben Young <computermouth@crunchbangplusplus.org>
-# for #!++ <https://crunchbangplusplus.org>
+# Ported to #!++ <https://crunchbangplusplus.org>
+# by Ben Young <computermouth@crunchbangplusplus.org>
 # --------------------------------------------------------------------
-# Set some variables
-USERDBDIR='/home/'$USER'/.dropbox-dist'
-TMPFILE='/tmp/'$USERNAME'_cbppdropbox'
+
+PROMPT_DELAY_TEXT='It is a good idea to add a delay before autostarting Dropbox
+so that your system can establish a working network connection.
+
+Select the number of seconds to delay Dropbox autostarting.
+Click "Cancel" if you do not want to add a delay.'
+PROMPT_DELAY_VARIANTS=(FALSE 10 FALSE 20 FALSE 30 FALSE 40 FALSE 50 TRUE 60)
+
+USERDBDIR="$HOME/.dropbox-dist/"
+
+
+if ! . cbpp-include.cfg 2> /dev/null; then
+    echo '  Failed to locate cbpp-include.cfg in PATH' >&2
+    exit 1
+fi
+
 # --------------------------------------------------------------------
 # manipulation
 # --------------------------------------------------------------------
-if [ "$1" = "--start-dropbox" ]; then
-    $USERDBDIR/dropboxd &
-    exit 0
-fi
-if [ "$1" = "--stop-dropbox" ]; then
-    killall dropbox
-    exit 0
-fi
-# --------------------------------------------------------------------
-# installation
-# --------------------------------------------------------------------
-if [ "$1" = "--install-dropbox" ]; then
-    zenity --question --title="Dropbox Installation" --text "This script will install Dropbox.\nDo you want to proceed?"
-    if [ $? = 1 ]; then
-        exit 0
-    fi
 
-    cd /home/$USER
+if [[ $1 = '--start-dropbox' ]]; then
+    "$USERDBDIR/dropboxd" &
     
-    platform=`uname -m | tr '[A-Z]' '[a-z]'`
+elif [[ $1 = '--stop-dropbox' ]]; then
+    killall dropbox
+    
+elif [[ $1 = '--install-dropbox' ]]; then
+    zenity --question --title='Dropbox Installation' --text 'This script will install Dropbox.\nDo you want to proceed?' || exit 0
+    
+    if ! cd "$HOME"; then # TODO Change directory? What for? Better use absolute paths
+        echo "Unable to change directory to $HOME"
+        exit 1
+    fi
+    
+    platform=$(uname -m)
+    platform=${platform,,}
+    
     case $platform in
-    "x86_64")
-        DROPBOXURL="https://www.dropbox.com/download?plat=lnx.x86_64"
+    'x86_64')
+        #DROPBOXURL='http://packages.crunchbang.org/waldorf-files/dropbox/64/dropbox.tar.gz'
+        DROPBOXURL='http://www.dropbox.com/download?plat=lnx.x86_64'
         ;;
     *)
-        DROPBOXURL="https://www.dropbox.com/download?plat=lnx.x86"
+        #DROPBOXURL='http://packages.crunchbang.org/waldorf-files/dropbox/32/dropbox.tar.gz'
+        DROPBOXURL='http://www.dropbox.com/download?plat=lnx.x86'
         ;;
     esac
     
-    
-    curl -s -I  $DROPBOXURL > $TMPFILE
-	CURLRESULT=`echo $?`
-	if [ $CURLRESULT = "0" ]; then
-		
-		RESPONSE=`head -n 1 $TMPFILE | awk '{ print $2 }'`
-		
-		#if [ $RESPONSE -ne "200" ]; then
-		if [ $RESPONSE -ne "302" ]; then
-			
-			zenity --warning --title="Dropbox Installation" --text "Error, failed to contact server. Please try again later."
-			exit 1
-		
-		else
-			
-			wget "$DROPBOXURL" 2>&1 | \
+    shitTemp=$(mktemp -u)
+    curl -s -I "$DROPBOXURL" > "$shitTemp"
+    if [[ $? = 0 ]]; then # TODO this check is just wrong. It doesn't even make sure if it is possible to download a file or not.
+        read _ RESPONSE _ <<< $(head -n 1 "$shitTemp")
+        
+        #if [ $RESPONSE -ne "200" ]; then
+        if [[ RESPONSE != 302 ]]; then
+            zenity --warning --title='Dropbox Installation' --text 'Error, failed to contact server. Please try again later.'
+            exit 1
+        else
+            dropboxFile=$(mktemp -u)
+            wget "$DROPBOXURL" -O "$dropboxFile" 2>&1 | \
              sed -u 's/^.* \+\([0-9]\+%\) \+\([0-9.]\+[GMKB]\) \+\([0-9hms.]\+\).*$/\1\n# Downloading... \2 (\3)/' | \
              zenity --progress --title='Installing Dropbox' --auto-kill --auto-close
-			
-		fi
-
-	else
-
-        zenity --warning --title="Dropbox Installation" --text "Error, failed to contact server. Please try again later."
-		exit 1
-
-	fi
-	
-	#rename binary
-	if [ -f /home/$USER/download?plat=lnx.x86_64 ]; then
-		mv /home/$USER/download?plat=lnx.x86_64 /home/$USER/dropbox.tar.gz
-	fi
-	if [ -f /home/$USER/download?plat=lnx.x86 ]; then
-		mv /home/$USER/download?plat=lnx.x86 /home/$USER/dropbox.tar.gz
-	fi
-    sleep 1s
-
-    #extract binary
-    tar -xf dropbox.tar.gz
-    #delete binary
-    rm dropbox.tar.gz
-    
-    #quick sanity check
-    if [ ! -x "$USERDBDIR/dropboxd" ]; then
-        zenity --warning --title="Dropbox Installation" --text "Oops! There was an error, Dropbox could not be installed. Sorry."
+        fi
+    else
+        zenity --warning --title='Dropbox Installation' --text 'Error, failed to contact server. Please try again later.'
         exit 1
     fi
-    zenity --info --title="Dropbox Installation" --text "Dropbox has been installed to:\n$USERDBDIR"
-    zenity --question --title="Dropbox Installation" --text "Dropbox can be started automatically when you start your session. Would you like to autostart Dropbox when you login?"
-    if [ $? != 1 ]; then
-        ans=$(zenity  --title="Dropbox Installation" --list  --text "It is a good idea to add a delay before autostarting Dropbox\nso that your system can establish a working network connection.\n\nSelect the number of seconds to delay Dropbox autostarting.\nClick \"Cancel\" if you do not want to add a delay." \
-        --radiolist  --column "Pick" --column "Seconds:" FALSE 10 FALSE 20 FALSE 30 FALSE 40 FALSE 50 TRUE 60);
-        if [ "$ans" != "" ]; then
-            echo $ans
-            echo "" >> /home/$USER/.config/openbox/autostart
-            echo "# Autostart the Dropbox deamon" >> /home/$USER/.config/openbox/autostart
-            echo "(sleep "$ans"s && ~/.dropbox-dist/dropboxd) &" >> /home/$USER/.config/openbox/autostart
-            echo "" >> /home/$USER/.config/openbox/autostart
-        else
-            echo "" >> /home/$USER/.config/openbox/autostart
-            echo "# Autostart the Dropbox deamon" >> /home/$USER/.config/openbox/autostart
-            echo "~/.dropbox-dist/dropboxd &" >> /home/$USER/.config/openbox/autostart
-            echo "" >> /home/$USER/.config/openbox/autostart
+    
+    #extract binary
+    tar -xf "$dropboxFile"
+    #delete binary archive
+    rm "$dropboxFile"
+    
+    #quick sanity check
+    if [[ ! -x $USERDBDIR/dropboxd ]]; then
+        zenity --warning --title='Dropbox Installation' --text 'Oops! There was an error, Dropbox could not be installed. Sorry.'
+        exit 1
+    fi
+    zenity --info --title='Dropbox Installation' --text "Dropbox has been installed to:\n$USERDBDIR"
+    zenity --question --title='Dropbox Installation' --text 'Dropbox can be started automatically when you start your session. Would you like to autostart Dropbox when you login?'
+    if [[ $? = 0 ]]; then # add to autostart!
+        ans=$(zenity  --title='Dropbox Installation' --list --text  "$PROMPT_DELAY_TEXT" --radiolist  --column 'Pick' --column 'Seconds:' "${PROMPT_DELAY_VARIANTS[@]}")
+        if [[ $? = 0 ]]; then
+            echo >> "$HOME/.config/openbox/autostart"
+            echo '# Autostart the Dropbox deamon' >> "$HOME/.config/openbox/autostart"
+            echo "(sleep ${ans}s && \"\$HOME/.dropbox-dist/dropboxd\") &" >> "$HOME/.config/openbox/autostart"
+            echo >> "$HOME/.config/openbox/autostart"
         fi
     fi
-    zenity --question --title="Dropbox Installation" --text "Do you wish to start the Dropbox client now?"
-    if [ $? = 1 ]; then
-        exit 0
-    fi
-    $USERDBDIR/dropboxd &
-    exit 0
-fi
-# --------------------------------------------------------------------
-# pipemenu stuff
-# --------------------------------------------------------------------
-# Check if user has installed Dropbox and offer to install it if not
-if [ ! -d $USERDBDIR ]; then
-    cat << _dropboxnotinstalledmenu_
-    <openbox_pipe_menu>
-	    <item label="Install Dropbox">
-            <action name="Execute">
-				<command>
-					cbpp-dropbox-pipemenu --install-dropbox
-				</command>
-			</action>
-		</item>
-		<separator/>
-		<item label="Find out more about Dropbox">
-            <action name="Execute">
-				<command>
-					x-www-browser http://db.tt/5mJg9lb
-				</command>
-			</action>
-		</item>
-		<item label="Dropbox Terms">
-            <action name="Execute">
-				<command>
-					x-www-browser https://www.dropbox.com/terms
-				</command>
-			</action>
-		</item>
-    </openbox_pipe_menu>
-_dropboxnotinstalledmenu_
-    exit 0
+    zenity --question --title='Dropbox Installation' --text 'Do you wish to start the Dropbox client now?' || exit 0
+    
+    "$USERDBDIR/dropboxd" &
 else
-    echo "<openbox_pipe_menu>"
-    if [ -d /home/$USER/Dropbox ]; then
-        cat << _dropboxhomedirlink_
-        <item label="Open Dropbox Folder">
-            <action name="Execute">
-				<command>
-					thunar /home/$USER/Dropbox
-				</command>
-			</action>
-		</item>
-_dropboxhomedirlink_
-    fi
-    if [ ! "$(pidof dropbox)" ]; then
-        cat << _startdropbox_
-        <item label="Start Dropbox">
-            <action name="Execute">
-				<command>
-					cbpp-dropbox-pipemenu --start-dropbox
-				</command>
-			</action>
-		</item>
-_startdropbox_
+    # pipemenu stuff
+    menuStart
+    if [[ ! -d $USERDBDIR ]]; then
+        menuItem 'Install Dropbox' 'cbpp-dropbox-pipemenu --install-dropbox'
+        menuSeparator
+        menuItem 'Find out more about Dropbox' 'x-www-browser http://db.tt/5mJg9lb'
     else
-    cat << _stopdropbox_
-        <item label="Stop Dropbox">
-            <action name="Execute">
-				<command>
-					cbpp-dropbox-pipemenu --stop-dropbox
-				</command>
-			</action>
-		</item>
-_stopdropbox_
+        [[ -d $HOME/Dropbox ]] &&
+            menuItem 'Open Dropbox Folder' 'thunar $HOME/Dropbox'
+        
+        if ! pidof dropbox > /dev/null; then
+            menuItem 'Start Dropbox' 'cbpp-dropbox-pipemenu --start-dropbox'
+        else
+            menuItem 'Stop Dropbox' 'cbpp-dropbox-pipemenu --stop-dropbox'
+        fi
+        menuSeparator
+        menuItem 'Launch Dropbox Website' 'x-www-browser https://www.dropbox.com/home'
     fi
-    cat << _dropboxinfomenu_
-    <separator/>
-		<item label="Launch Dropbox Website">
-            <action name="Execute">
-				<command>
-					x-www-browser https://www.dropbox.com/home
-				</command>
-			</action>
-		</item>
-		<item label="Dropbox Terms">
-            <action name="Execute">
-				<command>
-					x-www-browser https://www.dropbox.com/terms
-				</command>
-			</action>
-		</item>
-    </openbox_pipe_menu>
-_dropboxinfomenu_
-    exit 0
+    menuItem 'Dropbox Terms' 'x-www-browser https://www.dropbox.com/terms'
+    menuEnd
 fi
+exit 0
diff --git a/cbpp-pipemenus/data/usr/bin/cbpp-help-pipemenu b/cbpp-pipemenus/data/usr/bin/cbpp-help-pipemenu
--- a/cbpp-pipemenus/data/usr/bin/cbpp-help-pipemenu
+++ b/cbpp-pipemenus/data/usr/bin/cbpp-help-pipemenu
@@ -1,43 +1,29 @@
-#!/bin/sh
-cat << _EOF_
-<openbox_pipe_menu>
-    <separator label="Online Help"/>
-    <menu id="OpenboxWWW" label="Openbox">
-        <item label="Openbox Homepage">
-		    <action name="Execute">
-			    <command>
-				    x-www-browser "http://openbox.org/wiki/Main_Page"
-			    </command>
-		    </action>
-	    </item>
-	    <item label="Openbox Documentation">
-		    <action name="Execute">
-			    <command>
-				    x-www-browser "http://openbox.org/wiki/Help:Contents"
-			    </command>
-		    </action>
-	    </item>
-	    <item label="Openbox FAQ">
-		    <action name="Execute">
-			    <command>
-				    x-www-browser "http://openbox.org/wiki/Help:FAQ"
-			    </command>
-		    </action>
-	    </item>
-	    <item label="Openbox Getting Started">
-		    <action name="Execute">
-			    <command>
-				    x-www-browser "http://openbox.org/wiki/Help:Getting_started"
-			    </command>
-		    </action>
-	    </item>
-	    <item label="Openbox Community Portal">
-		    <action name="Execute">
-			    <command>
-				    x-www-browser "http://openbox.org/wiki/Openbox:Community_portal"
-			    </command>
-		    </action>
-	    </item>
-	</menu>
-</openbox_pipe_menu>
-_EOF_
+#!/bin/bash
+if ! . cbpp-include.cfg 2> /dev/null; then
+    echo '  Failed to locate cbpp-include.cfg in PATH' >&2
+    exit 1
+fi
+
+menuStart
+menuSeparator 'Online Help'
+menuItem 'Frequently Asked Questions' 'x-www-browser http://crunchbanglinux.org/wiki/faq'
+menuItem 'Tips, Scripts &amp; Tricks' 'x-www-browser http://crunchbanglinux.org/forums/topic/378/quick-reference/'
+menuItem 'Themes Guide' 'x-www-browser http://crunchbanglinux.org/wiki/theming'
+menuSeparator
+
+menuSubmenu 'CrunchBangWWW' 'CrunchBang Linux'
+menuItem 'CrunchBang Linux Homepage' 'x-www-browser http://crunchbanglinux.org/'
+menuItem 'CrunchBang Linux Wiki Pages' 'x-www-browser http://crunchbanglinux.org/wiki/'
+menuItem 'CrunchBang Linux Forums' 'x-www-browser http://crunchbanglinux.org/forums/'
+menuItem 'CrunchBang Linux Blog' 'x-www-browser http://crunchbanglinux.org/blog/'
+menuItem 'CrunchBang Linux Planet' 'x-www-browser http://crunchbanglinux.org/planet/'
+menuSubmenuEnd
+
+menuSubmenu 'OpenboxWWW' 'Openbox'
+menuItem 'Openbox Homepage' 'x-www-browser "http://openbox.org/wiki/Main_Page"'
+menuItem 'Openbox Documentation' 'x-www-browser "http://openbox.org/wiki/Help:Contents"'
+menuItem 'Openbox FAQ' 'x-www-browser "http://openbox.org/wiki/Help:FAQ"'
+menuItem 'Openbox Getting Started' 'x-www-browser "http://openbox.org/wiki/Help:Getting_started"'
+menuItem 'Openbox Community Portal' 'x-www-browser "http://openbox.org/wiki/Openbox:Community_portal"'
+menuSubmenuEnd
+menuEnd
diff --git a/cbpp-pipemenus/data/usr/bin/cbpp-x-www-browser-pipemenu b/cbpp-pipemenus/data/usr/bin/cbpp-x-www-browser-pipemenu
--- a/cbpp-pipemenus/data/usr/bin/cbpp-x-www-browser-pipemenu
+++ b/cbpp-pipemenus/data/usr/bin/cbpp-x-www-browser-pipemenu
@@ -2,414 +2,136 @@
 # ---------------------------------------------------------------------
 # Written for CrunchBang Linux <http://crunchbang.org/>
 # by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
-# updated by Ben Young <computermouth@crunchbangplusplus.org>
-# for #!++ <https://crunchbangplusplus.org>
+# Ported to #!++ <https://crunchbangplusplus.org>
+# by Ben Young <computermouth@crunchbangplusplus.org>
 # ---------------------------------------------------------------------
 
-pathto=$(readlink -f "$0" | sed 's%/*[^/]\+/*$%%')
 
-if [[ -f $pathto/cbpp-include.cfg ]]
-then
-    source "$pathto/cbpp-include.cfg"
-else
-    echo "  Failed to locate cbpp-include.cfg"
+# In order to add another browser, simply add it to this array:
+TOOLS=('chromium' 'iceweasel' 'google-chrome-stable' 'opera')
+# If the package needs additional configuration before installation simply create a function called setupBrowserName, it will be called automatically.
+
+KEY_URLS_GOOGLE=('https://dl-ssl.google.com/linux/linux_signing_key.pub' 'http://packages.crunchbang.org/waldorf-files/apt-keys/google-chrome.key')
+KEY_URLS_OPERA=('http://deb.opera.com/archive.key' 'http://packages.crunchbang.org/waldorf-files/apt-keys/opera.key')
+
+if ! . cbpp-include.cfg 2> /dev/null; then
+    say 'Failed to locate cbpp-include.cfg in PATH' >&2
     exit 1
 fi
 
-google_key_url_1='https://dl-ssl.google.com/linux/linux_signing_key.pub'
-google_key_url_2='http://packages.crunchbang.org/waldorf-files/apt-keys/google-chrome.key'
-opera_key_url_1='http://deb.opera.com/archive.key'
-opera_key_url_2='http://packages.crunchbang.org/waldorf-files/apt-keys/opera.key'
-I=0
+browserExists() {
+    for curTool in "${TOOLS[@]}"; do # if $packageName exists in tools array
+        [[ $curTool = "$1" ]] &&
+            return 0
+    done
+    say "Unable to install $1. There is no such browser that I know of." >&2
+    say "You can try one of these: ${TOOLS[@]}" >&2
+    return 1
+}
 
-if [ "$1" = "--chromium-browser" ]; then
-    terminator --title="Install Chromium Browser" --command="cbpp-x-www-browser-pipemenu --install-chromium-browser"
-    exit 0
-fi
-
-if [ "$1" = "--iceweasel" ]; then
-    terminator --title="Install Iceweasel Browser" --command="cbpp-x-www-browser-pipemenu --install-iceweasel"
-    exit 0
-fi
-
-if [ "$1" = "--google-chrome" ]; then
-    terminator --title="Install Google Chrome" --command="cbpp-x-www-browser-pipemenu --install-google-chrome"
-    exit 0
-fi
-
-if [ "$1" = "--opera" ]; then
-    terminator --title="Install Opera Browser" --command="cbpp-x-www-browser-pipemenu --install-opera"
-    exit 0
-fi
-
-if [ "$1" = "--install-chromium-browser" ]; then
+addAptKey() {
     clear
-    echo ""
-    echo "  INSTALL CHROMIUM BROWSER"
-    echo "  ------------------------"
-    echo "  This script will install Chromium."
-    echo ""
-    echo -n "  Run the installer now? (Y|n) > "
-    read a
-    if [ "$a" = "y" ] || [ "$a" = "Y" ] || \
-    [ "$a" = "" ]; then
-        
-        connectiontest
-        clear
-        echo "  Updating sources..."
-		sleep 2s
-		sudo apt-get update
-		clear
-        
-        
-        if ! sudo apt-get install -y chromium; then
-            clear
-            echo ""
-            echo "  There was a problem installing Chromium."
-            echo ""
-            echo "  Hit any key to try again, or \"q\" to quit..."
-            read -n1 a
-            if [ "$a" = "q" ] || [ "$a" = "Q" ]; then
-                clear
-                exit 0
-            else
-                cbpp-x-www-browser-pipemenu --install-chromium-browser
-                exit 0
-            fi
-        else
-            clear
-            echo ""
-            echo "  Chromium has been installed successfully."
-            echo ""
-            echo "  Hit any key to exit..."
-            read -n1 a
-            exit 0
-        fi
-    else
-        exit 0
+    say 'Adding APT key...'
+    keyFile=$(mktemp -u)
+    for curKey; do
+        wget -O "$keyFile" "$curKey" 2> /dev/null && break; # success. No need to try other keys
+        say "Failed to retrieve key from $curKey . Trying another source..."
+    done
+    if [[ $? != 0 ]]; then
+        say 'Failed to retrieve APT key!' >&2
+        return 1
     fi
-fi
+    sudo apt-key add "$keyFile"
+    rm -f "$keyFile"
+    return 0
+}
 
-if [ "$1" = "--install-iceweasel" ]; then
-    clear
-    echo ""
-    echo "  INSTALL ICEWEASEL BROWSER"
-    echo "  -------------------------"
-    echo "  This script will install Iceweasel."
-    echo ""
-    echo -n "  Run the installer now? (Y|n) > "
-    read a
-    if [ "$a" = "y" ] || [ "$a" = "Y" ] || \
-    [ "$a" = "" ]; then
+setupGooglechromestable() {
+    addAptKey "${KEY_URLS_GOOGLE[@]}" || return 1
+    say 'Creating APT sources file...' 1
+    echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee '/etc/apt/sources.list.d/google-chrome.list'
+}
+
+setupOpera() {
+    addAptKey "${KEY_URLS_OPERA[@]}" || return 1
+    say 'Creating APT sources file...' 1
+    echo 'deb http://deb.opera.com/opera/ stable non-free' | sudo tee '/etc/apt/sources.list.d/opera.list'
+}
+
+if [[ $1 && ! $1 =~ --install-* ]]; then
+    browserExists "${1:2}" || exit 1
+    browserName=${1:2}
+    browserName=${browserName//-/ }
+    terminator --title="Install ${browserName~}" --command="cbpp-x-www-browser-pipemenu --install-${1:2}"
+    
+elif [[ $1 = --install-* ]]; then
+    packageName=${1#--install-}
+    browserName=${packageName//-/ }
+    browserName=${browserName~}
+    browserNameUpper=${browserName^^}
+    
+    browserExists "$packageName" || exit 1
+
+    while true; do # do it until the package is successfully installed or user wants to exit
+        if [[ $TRYAGAIN ]]; then # previous try failed
+            say
+            say "There was a problem installing $browserName."
+            say
+            prompt '  Hit any key to try again, or "q" to quit...' Q && break
+        fi
+        TRYAGAIN=true
         
-        connectiontest
         clear
-        echo "  Updating sources..."
-		sleep 2s
-		sudo apt-get update
-		clear
+        say
+        say "INSTALL ${browserNameUpper% BROWSER} BROWSER"
+        say '------------------------'
+        say "This script will install $browserName."
+        say
+        prompt '  Run the installer now?' || break
         
-        
-        if ! sudo apt-get install -y iceweasel; then
-            clear
-            echo ""
-            echo "  There was a problem installing Iceweasel."
-            echo ""
-            echo "  Hit any key to try again, or \"q\" to quit..."
-            read -n1 a
-            if [ "$a" = "q" ] || [ "$a" = "Q" ]; then
-                clear
-                exit 0
-            else
-                cbpp-x-www-browser-pipemenu --install-iceweasel
-                exit 0
-            fi
-        else
-            clear
-            echo ""
-            echo "  Iceweasel has been installed successfully."
-            echo ""
-            echo "  Hit any key to exit..."
-            read -n1 a
-            exit 0
-        fi
-    else
-        exit 0
-    fi
-fi
-
-if [ "$1" = "--install-google-chrome" ]; then
-    clear
-    echo ""
-    echo "  INSTALL GOOGLE CHROME WWW BROWSER"
-    echo "  ---------------------------------"
-    echo "  This script will install Google Chrome."
-    echo ""
-    echo -n "  Run the installer now? (Y|n) > "
-    read a
-    if [ "$a" = "y" ] || [ "$a" = "Y" ] || \
-    [ "$a" = "" ]; then
-        
-        connectiontest
-        
-        #add apt-key
         clear
-        echo "  Adding APT key..."
-        sleep 2s
-        if ! wget -O google.key ${google_key_url_1} 2> /dev/null
-        then
-            # Fallback to packages.crunchbang.org.
-            if ! wget -O google.key ${google_key_url_2} 2> /dev/null
-            then
-                echo "  Failed to retrieve APT key from Google Inc."
-                clear
-                exit 1
-            fi
+        connectiontest 1 || continue
+        
+        setupFunctionName="setup${browserName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupChromiumBrowser'
+        if [[ $(type -t "$setupFunctionName") == 'function' ]]; then
+            "$setupFunctionName" || continue # run setup function if it exists
         fi
-        sudo apt-key add google.key
-        rm -f google.key
         
-        #create sources file
-        echo "  Creating APT sources file..."
-        sleep 2s
-        if [ -f "/etc/apt/sources.list.d/google-chrome.list" ]; then
-            sudo rm -f /etc/apt/sources.list.d/google-chrome.list
-        fi
-        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
-        
-        #update sources
-        echo "  Updating sources..."
-		sleep 2s
-		sudo apt-get update
-		clear
-        
-        
-        if ! sudo apt-get install -y google-chrome-stable; then
-            clear
-            echo ""
-            echo "  There was a problem installing Google Chrome."
-            echo ""
-            echo "  Hit any key to try again, or \"q\" to quit..."
-            read -n1 a
-            if [ "$a" = "q" ] || [ "$a" = "Q" ]; then
-                clear
-                exit 0
-            else
-                cbpp-x-www-browser-pipemenu --install-google-chrome
-                exit 0
-            fi
-        else
-            clear
-            echo ""
-            echo "  Google Chrome has been installed successfully."
-            echo ""
-            echo "  Hit any key to exit..."
-            read -n1 a
-            exit 0
-        fi
-    else
-        exit 0
-    fi
-fi
-
-if [ "$1" = "--install-opera" ]; then
-    clear
-    echo ""
-    echo "  INSTALL OPERA WWW BROWSER"
-    echo "  -------------------------"
-    echo "  This script will install Opera."
-    echo ""
-    echo -n "  Run the installer now? (Y|n) > "
-    read a
-    if [ "$a" = "y" ] || [ "$a" = "Y" ] || \
-    [ "$a" = "" ]; then
-        
-        connectiontest
-        
-        #add apt-key
         clear
-        echo "  Adding APT key..."
-        sleep 2s
-        if ! wget -O opera.key ${opera_key_url_1} 2> /dev/null
-        then
-            # Fallback to packages.crunchbang.org.
-            if ! wget -O opera.key ${opera_key_url_2} 2> /dev/null
-            then
-                echo "  Failed to retrieve APT key from Opera Software ASA."
-                clear
-                exit 1
-            fi
-        fi
-        sudo apt-key add opera.key
-        rm -f opera.key
+        say 'Updating sources...' 1
+        sudo apt-get update
         
-        #create sources file
-        echo "  Creating APT sources file..."
-        sleep 2s
-        if [ -f "/etc/apt/sources.list.d/opera.list" ]; then
-            sudo rm -f /etc/apt/sources.list.d/opera.list
-        fi
-        echo "deb http://deb.opera.com/opera/ stable non-free" | sudo tee -a /etc/apt/sources.list.d/opera.list
-        #update sources
-        echo "  Updating sources..."
-		sleep 2s
-		sudo apt-get update
-		clear
+        clear
+        say 'Installing package...' 1
+        sudo apt-get install -y "$packageName" || continue
         
-        
-        if ! sudo apt-get install -y opera; then
-            clear
-            echo ""
-            echo "  There was a problem installing Opera."
-            echo ""
-            echo "  Hit any key to try again, or \"q\" to quit..."
-            read -n1 a
-            if [ "$a" = "q" ] || [ "$a" = "Q" ]; then
-                clear
-                exit 0
-            else
-                cbpp-x-www-browser-pipemenu --install-opera
-                exit 0
-            fi
+        clear
+        say
+        say "$browserName has been installed successfully."
+        say
+        say 'Hit any key to exit...'
+        read -srn1
+        break
+    done
+else # pipemenu
+    menuStart
+    for curTool in "${TOOLS[@]}"; do
+        curToolName=${curTool//-/ }
+        curToolName=${curToolName~}
+        if [[ -x /usr/bin/$curTool ]]; then
+            INSTALLED=true
+            menuItem "$curToolName" "$curTool"
+            [[ $curToolName =~ 'Chrom' ]] &&
+                menuItem "$curToolName (Private Mode)" "$curTool --incognito" # Incognito mode for chrome and chromium
         else
-            clear
-            echo ""
-            echo "  Opera has been installed successfully."
-            echo ""
-            echo "  Hit any key to exit..."
-            read -n1 a
-            exit 0
+            menuItem "Install $curToolName" "cbpp-x-www-browser-pipemenu --$curTool"
         fi
-    else
-        exit 0
+    done
+
+    if [[ $INSTALLED ]]; then
+        menuSeparator
+        menuItem 'Select default browser' 'terminator --command="sudo update-alternatives --config x-www-browser"'
     fi
+    menuEnd
 fi
-# Start pipemenu
-echo "    <openbox_pipe_menu>"
-
-# Chromium
-if [ -x "/usr/bin/chromium" ];then
-    I=$((I+1))
-    cat << _menu_
-	    <item label="Chromium Browser">
-            <action name="Execute">
-				<command>
-					chromium
-				</command>
-			</action>
-		</item>
-		<item label="Chromium Browser (Private Mode)">
-            <action name="Execute">
-				<command>
-					chromium --incognito
-				</command>
-			</action>
-		</item>
-_menu_
-else
-	cat << _menu_
-	    <item label="Install Chromium Browser">
-            <action name="Execute">
-				<command>
-					cbpp-x-www-browser-pipemenu --chromium-browser
-				</command>
-			</action>
-		</item>
-_menu_
-fi
-
-# Iceweasel
-if [ -x "/usr/bin/iceweasel" ];then
-    I=$((I+1))
-    cat << _menu_
-	    <item label="Iceweasel">
-            <action name="Execute">
-				<command>
-					iceweasel
-				</command>
-			</action>
-		</item>
-_menu_
-else
-	cat << _menu_
-	    <item label="Install Iceweasel">
-            <action name="Execute">
-				<command>
-					cbpp-x-www-browser-pipemenu --iceweasel
-				</command>
-			</action>
-		</item>
-_menu_
-fi
-
-# Google Chrome
-if [ -x "/usr/bin/google-chrome" ];then
-    I=$((I+1))
-    cat << _menu_
-	    <item label="Google Chrome">
-            <action name="Execute">
-				<command>
-					google-chrome
-				</command>
-			</action>
-		</item>
-		<item label="Google Chrome (Private Mode)">
-            <action name="Execute">
-				<command>
-					google-chrome --incognito
-				</command>
-			</action>
-		</item>
-_menu_
-else
-	cat << _menu_
-	    <item label="Install Google Chrome">
-            <action name="Execute">
-				<command>
-					cbpp-x-www-browser-pipemenu --google-chrome
-				</command>
-			</action>
-		</item>
-_menu_
-fi
-
-# Opera
-if [ -x "/usr/bin/opera" ];then
-    I=$((I+1))
-    cat << _menu_
-	    <item label="Opera">
-            <action name="Execute">
-				<command>
-					opera
-				</command>
-			</action>
-		</item>
-_menu_
-else
-	cat << _menu_
-	    <item label="Install Opera">
-            <action name="Execute">
-				<command>
-					cbpp-x-www-browser-pipemenu --opera
-				</command>
-			</action>
-		</item>
-_menu_
-fi
-
-# Configure default
-if [ $I -gt 1 ];then
-    cat << _menu_
-	    <separator/>
-	    <item label="Select default browser">
-            <action name="Execute">
-				<command>
-					terminator --command="sudo update-alternatives --config x-www-browser"
-				</command>
-			</action>
-		</item>
-_menu_
-fi
-# End pipemenu
-echo "    </openbox_pipe_menu>"
 exit 0
